# Generated by Django 3.0.3 on 2020-03-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_slogin_cgpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slogin',
            name='cgpa',
            field=models.IntegerField(max_length=20),
        ),
    ]
