# Generated by Django 3.0.3 on 2020-03-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0004_auto_20200307_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slogin',
            name='tenth',
        ),
        migrations.AlterField(
            model_name='slogin',
            name='lang',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='slogin',
            name='phone_number',
            field=models.CharField(max_length=11),
        ),
    ]
