# Generated by Django 3.0.3 on 2020-03-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0005_auto_20200307_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='slogin',
            name='tenth',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slogin',
            name='twelth',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
