# Generated by Django 3.0.3 on 2020-03-07 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0008_stdb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='slogin',
        ),
    ]
