# Generated by Django 3.0.3 on 2020-03-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0009_delete_slogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='stdb',
            name='lang',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stdb',
            name='phone_number',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stdb',
            name='twe_m',
            field=models.IntegerField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
