# Generated by Django 3.0.3 on 2020-03-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0010_auto_20200307_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='stdb',
            name='cgpa',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stdb',
            name='twe_m',
            field=models.CharField(max_length=20),
        ),
    ]
