# Generated by Django 3.0.3 on 2020-03-10 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0013_stadb'),
    ]

    operations = [
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('com_name', models.CharField(max_length=100)),
                ('job_nature', models.CharField(max_length=30)),
                ('sal_range', models.CharField(max_length=20)),
                ('com_add', models.CharField(max_length=150)),
                ('reg_link', models.CharField(max_length=1000)),
                ('job_des', models.CharField(max_length=300)),
                ('com_city', models.CharField(max_length=100)),
            ],
        ),
    ]
