# Generated by Django 3.0.3 on 2020-03-10 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0014_job'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='job',
            new_name='job1',
        ),
    ]
