# Generated by Django 3.0.3 on 2020-03-14 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0016_auto_20200314_1916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stdb',
            old_name='first_name',
            new_name='fname',
        ),
    ]
